apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure
  - ../../infrastructure/cert-manager/application.yaml
  - ../../infrastructure/external-secrets/application.yaml
  - ../../infrastructure/monitoring/application.yaml
  - ../../infrastructure/keel/application.yaml
  - ../../infrastructure/argocd/application.yaml

  # Applications
  - ../../apps/n8n/application.yaml
  - ../../apps/supabase/application.yaml
